In [38]:
import torch

In [14]:
x = torch.tensor([[1,2,3], [4,5,6]])
x.shape

torch.Size([2, 3])

In [5]:
x.repeat(2,1)

tensor([[1, 2, 3],
        [4, 5, 6],
        [1, 2, 3],
        [4, 5, 6]])

In [15]:
torch.repeat_interleave(x, 5, dim=0)

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [4, 5, 6],
        [4, 5, 6],
        [4, 5, 6],
        [4, 5, 6],
        [4, 5, 6]])

In [35]:
from collections import defaultdict
x = defaultdict()

In [36]:
y = {"a":1, "b":2}

In [37]:
for key, item in y.items():
    x[key] += item

KeyError: 'a'

In [57]:
x = torch.tensor([0.1, 0.9, 0.7, 0.2, 0.5])
x = x > 0.5

In [59]:
o = torch.nonzero(x.long())

In [66]:
torch.nonzero(torch.tensor([0,1,2,3])).numpy().squeeze()

array([1, 2, 3], dtype=int64)

In [53]:
torch.tensor([0,1,2,3])

tensor([0, 1, 2, 3])

In [56]:
x.long()

tensor([0, 1, 0, 0, 0])

In [63]:
for i in o.numpy():
    print(i[0])

1
2
